fix(client): removing unused linting code

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,7 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-# Linting @semoss/client & @semoss/ui
+# Linting all staged files
 npx lint-staged --concurrent false --relative || {
   echo "ERROR: Linting issues were found. Please address them before proceeding."
   exit 1
@@ -14,7 +14,7 @@ npx lint-staged --concurrent false --relative || {
 # }
 
 # Testing all projects/libs if vite config is present
-# npx vitest --watch=false --passWithNoTests --changed || {
-#   echo "ERROR: Testing issues were found in the committed files. Please address them before proceeding."
-#   exit 1
-# }
+npx vitest --watch=false --passWithNoTests --changed || {
+  echo "ERROR: Testing issues were found in the committed files. Please address them before proceeding."
+  exit 1
+}
