chore: WIP updating build

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,15 +1,9 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-# Linting @semoss/client
-npx nx lint @semoss/client || {
-  echo "ERROR: Linting issues were found in the packages/client. Please address them before proceeding."
-  exit 1
-}
-
 # Linting @semoss/ui
-npx nx lint @semoss/ui || {
-  echo "ERROR: Linting issues were found in the libs/ui. Please address them before proceeding."
+pnpm run fix || {
+  echo "ERROR: Linting issues were found. Please address them before proceeding."
   exit 1
 }
 
