test(client): changing pre commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,17 +1,17 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-echo "Running pre-commit"
+# echo "Running pre-commit"
 
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACDMRTUXB* origin/dev | grep -E '\.(ts|js|tsx)$')
+# STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACDMRTUXB* origin/dev | grep -E '\.(ts|js|tsx)$')
 
-echo "Staged files are `$STAGED_FILES`"
+# echo "Staged files are `$STAGED_FILES`"
 
 # Linting all staged files
-# npx lint-staged --concurrent false --relative || {
-#   echo "ERROR: Linting issues were found. Please address them before proceeding."
-#   exit 1
-# }
+npx lint-staged --concurrent false --relative || {
+  echo "ERROR: Linting issues were found. Please address them before proceeding."
+  exit 1
+}
 
 # Linting @semoss/renderer
 # npx nx lint @semoss/renderer || {
